### ISSUE TITLE
Instructions don't specify paste for 2.5mm holes.

### ISSUE THREAD

**Issue by sequoia-hope** [Hoektronics/Stencil8#1]
On your website you mention that the 2.5mm holes need to be in the paste layer too, so that they end up in your stencil. However, the "PCB Fabrication Instructions.doc" on here (which is excellent!) doesn't specify that.

Can you add a bit in the instructions specifying that the holes should also be present on the paste layer?

Thanks!

**Comment by hoeken** [comment]
good call.  i've updated that text and am having it translated.  i'll push it once i verify it with my supplier.  luckily i need to do another run of boards that needs to be panelized like this.  :)

**Comment by sequoia-hope** [comment]
Awesome!

We'll be trying this through goldphoenix whenever we get around to our next
order. People in the US might be interested in finding out if goldphoenix
is willing to do this, so when I get a response I can let you know, if
you'd like to have that info on the blog post. I hope they will or I'll
have to figure out how to script this panelization...

**Comment by hoeken** [comment]
Cool, if you do end up having to do the panelization manually, I'd love to
get the script in the repository (assuming you're cool with that)

---

Zach Hoeken Smith

_Work:_ www.haxlr8r.com
_Blog:_ www.hoektronics.com
_Twitter:_ @hoeken  _Skype:_ chilldude22
_QQ:_ 1489598623  _China:_ +86-186-8209-7069

On Mon, Nov 19, 2012 at 10:01 PM, Taylor Alexander <notifications@github.com

> wrote:
> 
> Awesome!
> 
> We'll be trying this through goldphoenix whenever we get around to our
> next
> order. People in the US might be interested in finding out if goldphoenix
> is willing to do this, so when I get a response I can let you know, if
> you'd like to have that info on the blog post. I hope they will or I'll
> have to figure out how to script this panelization...
>

**Comment by sequoia-hope** [comment]
Absolutely cool with that! I try to open source anything I can. Plus the
panelization is a major step if the fab house won't do it, so being able to
do it easily would really help people with this. I was also going to offer
to share my gcode when I'm done. I'm making the code so that it hopefully
can be pretty easily adapted to another CNC machine, so it might be useful
to people that, say, have access to a Techshop or have a CNC at their
hackerspace.

**Comment by hoeken** [comment]
If you do make panelization code, it would be most useful to do it at the
GERBER level and allow it to accept multiple files at the same time, and do
the exact same panelization to all of them.  That way it would be useful
for all the pcb layout programs (kicad, eagle, etc.)

---

Zach Hoeken Smith

_Work:_ www.haxlr8r.com
_Blog:_ www.hoektronics.com
_Twitter:_ @hoeken  _Skype:_ chilldude22
_QQ:_ 1489598623  _China:_ +86-186-8209-7069

On Mon, Nov 19, 2012 at 10:31 PM, Taylor Alexander <notifications@github.com

> wrote:
> 
> Absolutely cool with that! I try to open source anything I can. Plus the
> panelization is a major step if the fab house won't do it, so being able
> to
> do it easily would really help people with this. I was also going to offer
> to share my gcode when I'm done. I'm making the code so that it hopefully
> can be pretty easily adapted to another CNC machine, so it might be useful
> to people that, say, have access to a Techshop or have a CNC at their
> hackerspace.
>

**Comment by sequoia-hope** [comment]
That's the plan! Our main designer still uses Protel from 1995 (yeah, I
don't even...) so we need to work at the gerber level.

I found some info on using gerbmerge (including tab routing stuff) here:
http://blog.omegacs.net/2011/05/26/panelizing-pcb-assembly-prepping-the-boards/

If I do sort something out, it's likely to be barebones, but i'll
definitely put it on github so people can use and fork it. It seems like
there's some trickery involved in getting gerbmerge to work properly, but
it really could use a front end so this could be a great start to that.

**Comment by sequoia-hope** [comment]
Awesome!
