### ISSUE TITLE
Incorrect tolerance on 2.5mm hole drawing (and they need a chamfer)

### ISSUE THREAD

**Issue by sequoia-hope** [Hoektronics/Stencil8#2]
(I was going to hit you up on google talk to avoid creating another issue but I realized it might be easier to keep track of the issue if, say, I used the issue tracker...)

If someone sends this drawing to a shop, they might end up with 2.4mm holes (as per the tolerance of 2.5mm +/- 0.1mm), and a 2.5mm pin won't fit into a 2.4mm hole (probably not even with a hammer, if its a steel pin in aluminum). This is especially likely in an American shop that might not have a 2.5mm drill, as a #40 or #41 drill are within that tolerance, but under 2.5mm.

Pins are usually very accurate too. Mcmaster# 91585A040 is dimensioned as 2.5mm +0.002/+0.008, meaning they are never under 2.5mm.

Typically for a good tight fit that you can still drop in and pull out by hand, you want around 0.0005-0.001 inches of clearance, so if you want to be able to fit pins like the ones from McMaster (and they don't sell undersized ones), you need a hole that is a minimum of 2.5135mm.

Figuring out the upper end is trickier. If you specify a really tight tolerance on a hole, the shop will do it but they'll charge you a bunch of money.

Since I never check the diameter of small holes I drill I don't actually know what an "easy" tolerance is, and I'm not an expert on slip fit holes, but a bit of googling turned up this page:
http://www.engineersedge.com/dowel_pin.htm

Which says that for a slip fit with a pin of this size, you want the hole to be 0.0015" oversized +/- 0.0005".

So I guess the hole call out should just be 2.54mm +/- 0.015mm (I rounded a bit)

Also, you should call out a chamfer on the hole of 0.5mm or so. Not sure how if your assistant will know how to say chamfer in chinese, but sometimes that is stated on drawings as "break all sharp edges" instead, so you could say that.

**Comment by hoeken** [comment]
awesome work!  I'll update that and add the chamfer information to boot.
 my cnc shop just automatically added the chamfer, but you're right that it
is a good idea to explicitly state that in the drawing.

---

Zach Hoeken Smith

_Work:_ www.haxlr8r.com
_Blog:_ www.hoektronics.com
_Twitter:_ @hoeken  _Skype:_ chilldude22
_QQ:_ 1489598623  _China:_ +86-186-8209-7069

On Tue, Nov 20, 2012 at 12:13 AM, Taylor Alexander <notifications@github.com

**Comment by sequoia-hope** [comment]
Update!

Finally got a 2.5mm drill and a #39 reamer (2.5273mm), so I did some tests.

Using our old drill press (not an ideal test as the spindle wobbles a bit, the speed is too slow, and there's no coolant, but setting up the CNC would have been a pain), gave me this:

2.5mm drill, no reamer:  
Pin fits in by hand, but is "sticky" and hole feels irregular. Some holes may jam.

Number 39 drill, no reamer:  
May work, but pin feels a bit too loose. The drill wasn't brand new though, so that could have been the issue.

2.5mm drill, followed by #39 (2.5273mm) reamer:  
Pin slips in nicely, hole is smooth. This is likely the best way to go.

I'll machine a plate and update if the CNC makes things too tight, though I don't foresee that happening with the reamer.

**Comment by hoeken** [comment]
It took a while, but I finally got around to this.  I made it 2.55mm +/-
0.02mm since I'm not sure they make 2.54mm drill bits.

The important part for me is finding the right supplier that can do these
holes well, and I got that in the bag.  For the DIY crowd the tip of drill
- ream is probably better than exactly the right tolerance spec.

---

Zach Hoeken Smith

_Work:_ www.haxlr8r.com
_Blog:_ www.hoektronics.com
_Twitter:_ @hoeken  _Skype:_ chilldude22
_QQ:_ 1489598623  _China:_ +86-186-8209-7069

**Comment by sequoia-hope** [comment]
Sounds good! I only work one day a week at the job where I was trying to get this setup, and I've been given other priorities since first trying to make this plate, so I still haven't made the damn thing beyond my hole tests.

But yeah, I just wanted to do some testing for people that aren't sure what to do, and provide some help for people who might end up with a supplier who accidentally would have made things wrong. Looks like your changes wrap this up though.

**Comment by liteplacerfanclub** [comment]
Hi, please undo this fix, it is totally wrong.

I just had the "new and wrong" files manufactured, the shop gave me exactly what's in the diagram, and none of my existing stencils and board work with it.  Total disaster.

This just cost me several hundred dollars.

Zach, the files in this repo need to describe the product you sold called "stencil8".  If you want to fiddle with the files, call the result something else.  Whatever it is, it isn't stencil8.

**Comment by sequoia-hope** [comment]
Hi!
Can you describe clearly what was wrong and why it didn't work?
Thanks.

**Comment by hoeken** [comment]
Whoa, I didnt sell anyone anything. Stencil8 was just a simple project I
shared a long time ago with a grid for aligning pcbs and solder stencils.
What went wrong?

On Monday, May 2, 2016, Taylor Alexander notifications@github.com wrote:

> Hi!
> Can you describe clearly what was wrong and why it didn't work?
> Thanks.
> On May 2, 2016 12:15 PM, "liteplacerfanclub" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Hi, please undo this fix, it is totally wrong.
> > 
> > I just had the "new and wrong" files manufactured, the shop gave me
> > exactly what's in the diagram, and none of my existing stencils and board
> > work with it. Total disaster.
> > 
> > This just cost me several hundred dollars.
> > 
> > Zach, the files in this repo need to describe the product you sold called
> > "stencil8". If you want to fiddle with the files, call the result
> > something
> > else. Whatever it is, it isn't stencil8.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Hoektronics/Stencil8/issues/2#issuecomment-216333357
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Hoektronics/Stencil8/issues/2#issuecomment-216337292

## 

---

Zach Hoeken Smith

_Work:_ www.haxlr8r.com
_Blog:_ www.hoektronics.com
_Twitter:_ @hoeken  _Skype:_ chilldude22
_QQ:_ 1489598623  _China:_ +86-186-8209-7069

**Comment by liteplacerfanclub** [comment]
Details are here: https://github.com/Hoektronics/Stencil8/issues/3

**Comment by liteplacerfanclub** [comment]
This is the official Stencil8 product that lots of people bought, which is no longer available for sale:

  https://www.tindie.com/products/arachnidlabs/pcb-tooling-block-full-grid/

You should make it clear that people seeking a replacement for their "Stencil8 PCB Tooling Block" should NOT use the files in your github "Stencil8 PCB Tooling Block" repository, because they do not match.  I'm pretty sure the vast majority of people who come across this git repo are here because they need a replacement or extra copy of their existing Stencil8 PCB Tooling Block, and they need it to match exactly in order to not spend enormous sums of money remaking all their stencils and boards.

As mentioned, full details are in issue #3 ("Drawings do not match product! Please warn people about this!!!").  I commented here because it appears that this thread spawned the problem.

**Comment by liteplacerfanclub** [comment]
FWIW, I had the machine shop re-run the entire job on the opposite side of the aluminum block using the schematics from before this commit, and the result is correct: the pins that fit all my existing boards+stencils (several hundred dollars worth of investment) also fit the tooling block (without any wobble).

The changes introduced in this commit are wrong.
